config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goods, only: [:index]

  # Cart routes
  resource :cart, only: [:show, :create, :destroy] do
    post :proceed
  end

  # Admin routes
  get "admin",  to: redirect('/admin/goods')

  namespace :admin do
    resources :goods, only: [:index, :update, :destroy, :create]
    # TODO: В данной версии у нас нет возможности создать и удалить администратора.
    #       Сделать это можно только через Базу Данных.
  end

  root 'goods#index'
end

app/models/good.rb
class Good < ActiveRecord::Base
  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # TODO: в базе данных у нас есть поле item_type, которое содержит в себе тип товара (Книга, программа, автомобиль и так далее)
  #       В данный момент мы нигде не используем это поле. Оно может пригодиться для каталогизации товаров,
  #         а также добавления специальной логики для того или иного типа товаров (например, цена на автомобиль
    #       должна быть не меньше 100000 рублей).

  def available?
    amount > 0
  end
end

app/models/online_cart.rb
# TODO: Данный класс по работе с корзиной использует объект сессии для хранения данных
#       Это не совсем удобно, так как сессия имеет ограниченное время жизни.
#       Как вариант, можно создать таблицу и хранить корзину пользователя там.
#       При этом данные не исчезнут, если пользователь закрыл браузер, например,
#         и будут доступны с любого браузера и устройства.

class OnlineCart
    def initialize(session:)
        @session = session
    end

    def goods
        @session[:goods] ||= {}
    end

    def self.goods(session:)
        new(session: session).goods
    end

    def self.get(good_id:, session:)
        new(session: session).goods[good_id.to_s].to_i
    end

    def self.ids(session:)
       new(session: session).goods.keys
    end

    def self.set(good_id:, good_amount:, session:)
        new(session: session).goods[good_id.to_s] = good_amount
    end

    def self.remove(good_id:, session:)
        new(session: session).goods.delete(good_id.to_s)
        true
    end

    def self.has_good?(good_id:, session:)
        new(session: session).goods.keys.include?(good_id.to_s)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  # Помимо проверки на аутентикацию пользователя, мы еще проверяем его
  #   права доступа. Если это не администратор, то перенаправляем запрос на
  #   главную страницу сайта
  before_action :user_must_be_admin!

  private

  def user_must_be_admin!
    redirect_to root_path unless current_user.is_admin
  end
end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < Admin::AdminController
  # TODO: В данной версии нашего интернет магазина мы не возвращаем информацию об ошибках и
  #         оставляем это на откуп администраторам, работающим с товарами. Это неудобно, так
  #         как не позволяет сразу идентифицировать проблему, возникшую во время той или иной
  #         операции с товаром.

  def create
    good = Good.new(good_params)
    good.save
    redirect_to admin_goods_path
  end

  def index
    @goods = Good.all
  end

  def update
    Good.find(params[:id]).update(good_params)
    redirect_to admin_goods_path
  end

  def destroy
    Good.find(params[:id]).destroy
    redirect_to admin_goods_path
  end

  private

  def good_params
    params.permit(:name, :price, :amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # TODO: Мы не авторизуем пользователей для страницы с корзиной.
  #       Это делается для упрощения нашего сайте. Так как мы все равно храним
  #         информацию о корзине пользователя в сессии, которая будет недоступна, если
  #         пользователь покинет сайт или зайдет на него с другого устройства или браузера,
  #         то хранение корзины в анонимной сессии является простым и эффективным способом.

  # TODO: В данной версии этого приложения мы не реагируем на ошибки, которые могут возникнуть в
  #         процессе работы нашего приложения. Это плохо, так как пользователь не сможет понять
  #         что пошло не так и что ему делать дальше.

  before_action :empty_flash, except: [:proceed]

  # TODO: На многих интернет магазинах принято спрашивать у пользователя о его дальнейших действиях.
  #       Возможно пользователь, после добавления товара в корзину желает продолжить ознакомление со
  #         список товаров на сайте и пока не готов перейти в корзину для оплаты.
  def create
    OnlineCart.set(
      good_id: params[:good_id],
      good_amount: OnlineCart.get(good_id: params[:good_id], session: session) + 1,
      session: session
    )
    load_cart

    redirect_to cart_path
  end

  def show
    load_cart
  end

  def destroy
    OnlineCart.remove(good_id: params[:good_id], session: session)
    load_cart

    redirect_to cart_path
  end

  def proceed
    # TODO: Данный метод можно (и нужно!) значительно улучшить. Например, разбить его на функции,
    #         например, одна будет подготавливать заказ пользователя, другая отправлять данные,
    #         третья, очищать коризну. Можно пойти еще дальше. Функцию очистки корзины перенести в
    #         класс OnlineCart. Другие функции вынести в concern Cart.

    load_cart
    order = Good.where(id: OnlineCart.ids(session: session)).map{|g| {item: g, count: OnlineCart.goods(session: session)[g.id.to_s]}}
    OrderMailer.order_email(user: order_params, order: order).deliver_now unless Rails.env.heroku?
    @goods.each do |good|
      OnlineCart.remove(good_id: good.id, session: session)
    end

    flash[:notice] = I18n.t('cart.order_sent')
    redirect_to cart_path
  end

  # TODO: В интернет магазинах также есть возможность изменить количество заказываемого товара.
  #       У нас для этого все готово. Есть метод OnlineCart.set, который позволяет изменять количество
  #         товара. Все, что нам остается сделать, это добавить метод #update в данный контроллер

  # TODO: Также имеет смысл добавить метод "destroy_all", который бы очищал карщину пользователя

  private

  def load_cart
    @goods = Good.where(id: OnlineCart.ids(session: session))
  end

  def order_params
    params.permit(:user_email, :user_phone, :user_address)
  end

  def empty_flash
    flash[:notice] = nil
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def index
    @goods = Good.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # TODO: Здесь мы используем самописное решение по склонению слов.
  #       В данном случае, для слова "товары"
  #       Существует gem "globalize" (https://github.com/globalize/globalize)
  #       в котором уже имеются все необходимые функции для склонения слов.
  def localize_goods(count)
    ending = count % 100
    if ending >= 11 && ending <= 19
      I18n.t('goods.plural.many')
    else
      ending = count % 10
      if ending == 1
        I18n.t('goods.plural.one')
      elsif ending > 1 && ending <=4
        I18n.t('goods.plural.other')
      else
        I18n.t('goods.plural.many')
      end
    end
  end
end

app/views/admin/goods/index.html.erb
<h2>Доступные товары</h2>

<% if @goods.size > 0 %>
  <table class="table table-condensed">
    <thead>
      <th>Название</th>
      <th>Цена</th>
      <th>Количество на складе</th>
      <th></th>
    </thead>
    <tbody>
      <% @goods.each do |good| %>
        <tr>
          <td><%= good.name %></td>
          <td><%= good.price %></td>
          <td>
            <%= form_tag admin_good_path(id: good.id), class: "well well-sm form-inline", method: "PUT" do %>
              <%= text_field_tag 'amount', good.amount, class: 'form-control', placeholder: 'Количество на складе' %>
              <%= button_tag(type: 'submit', class: 'btn btn-default') do
                 content_tag(:span, "Сохранить")
              end %>
              <%= link_to("Удалить", admin_good_path(id: good.id), method: "DELETE", class: "btn btn-danger") %>
            <% end %>
          </td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  В данный момент товары на складе отсутствуют!
<% end %>

<h3>Добавить товар</h3>

<%= form_tag admin_goods_path, class: "well", method: "POST" do %>
  <div class="form-group">
    <label for="name">Название</label>
    <%= text_field_tag('name', nil, class: 'form-control', placeholder: 'Название') %>
  </div>
  <div class="form-group">
    <label for="price">Цена</label>
    <%= text_field_tag 'price', '', class: 'form-control', placeholder: 'Цена' %>
  </div>
  <div class="form-group">
    <label for="amount">Количество на складе</label>
    <%= text_field_tag 'amount', '', class: 'form-control', placeholder: 'Количество на складе' %>
  </div>

  <%= button_tag(type: 'submit', class: 'btn btn-default') do
     content_tag(:span, "Сохранить")
  end %>
<% end %>

app/views/carts/_table.html.erb
<% "TODO: в данной версии корзины мы не выводим количество заказанного товара. Это неудобно для пользователя." %>

<table class="table table-condensed">
  <thead>
    <th><%= I18n.t("goods.table.good_name") %></th>
    <th><%= I18n.t("goods.table.price") %></th>
    <th></th>
  </thead>
  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <td><%= good.price %></td>
        <td><%= link_to(I18n.t("goods.table.remove"), cart_path(good_id: good.id), method: "DELETE") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% "TODO: блок с формой стоит вынести в отдельную View, так как он не относится напрямую к таблице" %>

<%= form_tag proceed_cart_path, class: "well", method: "POST" do %>
  <div class="form-group">
    <label for="user_email">Email</label>
    <%= email_field_tag('user_email', nil, class: 'form-control', placeholder: 'Email') %>
  </div>
  <div class="form-group">
    <label for="user_phone"><%= I18n.t('cart.user.phone') %></label>
    <%= text_field_tag 'user_phone', '', class: 'form-control', placeholder: I18n.t('cart.user.phone') %>
  </div>
  <div class="form-group">
    <label for="user_address"><%= I18n.t('cart.user.address') %></label>
    <%= text_field_tag 'user_address', '', class: 'form-control', placeholder: I18n.t('cart.user.address') %>
  </div>

  <%= button_tag(type: 'submit', class: 'btn btn-default') do
     content_tag(:span, I18n.t("cart.send_order"))
  end %>
<% end %>

app/views/carts/show.html.erb
<h2><%= I18n.t('cart.title') %></h2>

<% if flash[:notice].present? %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<p>
    <%= I18n.t('cart.in_cart', goods_count: "#{OnlineCart.ids(session: session).count} #{localize_goods(OnlineCart.ids(session: session).count)}") %>.
</p>

<% if OnlineCart.ids(session: session).count > 0 %>
  <% "TODO: Здесь мы используем отдельную копию partial-view для отображения таблицы с товарами. На данный момент единственная разница между partial-view из папки goods и папки carts в столбце со ссылками (добавить в корзину / удалить из корзины). Пока отличия небольшие, для упрощения нашего проекта лучше объеденить эти два partial-view в один." %>
  <%= render "table" %>
<% end %>

app/views/goods/_table.html.erb
<% "TODO: в данной версии нашего интернет магазина мы не показывает страницу с товаром. Это не удобно для пользователя." %>

<table class="table table-condensed">
  <thead>
    <th><%= I18n.t("goods.table.good_name") %></th>
    <th><%= I18n.t("goods.table.price") %></th>
    <th><%= I18n.t("goods.table.is_available") %></th>
    <th></th>
  </thead>
  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <td><%= good.price %></td>
        <td><%= I18n.t("goods.table.#{good.available? ? 'available' : 'not_available'}") %></td>
        <% "TODO: Строчка 15 слишком сложная. Имеет смысл вынести данный код в helper-метод и поместить его, например в app/helpers/goods_helper.rb Это избавит данный view от лишней логики и разделит работу backend и frontend разработчиков" %>
        <td>
          <% if good.amount.positive? %>
            <%= OnlineCart.has_good?(good_id: good.id, session: session) ? link_to(I18n.t("goods.table.in_cart"), cart_path) : link_to(I18n.t("goods.table.add_to_cart"), cart_path(good_id: good.id), method: 'POST') %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/goods/index.html.erb
<h2><%= I18n.t('goods.title') %></h2>

<p><%= link_to I18n.t('goods.your_cart', goods_count: "#{OnlineCart.ids(session: session).count} #{localize_goods(OnlineCart.ids(session: session).count)}"), cart_path %>

<% if @goods.size > 0 %>
  <%= render 'table' %>
<% else %>
  <%= I18n.t('goods.empty') %>
<% end %>

app/views/layouts/_admin_header.html.erb
<div class="page-header">
  <h1>Панель администратора</h1>
</div>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img alt="SuperOnlineShop" src="<%= asset_path 'favicon24.png' %>" width="20">
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Вернуться на сайт", root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Выход", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div>
    © SuperOnlineShop & <%= link_to "Андрей Ерёмин, #{Time.now.year}", "http://aeremin.ru", target: '_blank' %>
  </div>
<div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <h1><%= link_to(t('layout.header.title'), root_path) %></h1>
  <h5><%= t('layout.header.slogan') %></h5>
</div>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img alt="SuperOnlineShop" src="<%= asset_path 'favicon24.png' %>" width="20">
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= (current_page?(root_path) || current_page?(goods_path)) ? 'active' : '' %>"><%= link_to t('layout.footer.main_page'), goods_path %></li>

        <% "TODO: Нет смысла показывать ссылку на корзину, если в ней нет ни одного товара" %>
        <li class="<%= current_page?(cart_path) ? 'active' : '' %>"><%= link_to(t('layout.header.cart'), cart_path) %></li>

        <% if current_user && current_user.is_admin %>
          <li class="<%= current_page?(admin_goods_path) ? 'active' : '' %>"><%= link_to t('layout.footer.admin_page'), admin_goods_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= I18n.locale == :ru ? 'active' : '' %>"><%= link_to("РУ", {locale: 'ru'}) %></li>
        <li class="<%= I18n.locale == :en ? 'active' : '' %>"><%= link_to("EN", {locale: 'en'}) %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperOnlineShop - Панель администратора</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/admin_header" %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= I18n.t('layout.global.title') %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </div>
</body>
</html>